apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: mongodb
manifests:
  rawYaml: []

deploy:
  helm:
    
    releases:
      - name: mongodb
        #repo: oci://registry-1.docker.io/bitnamicharts/mongodb
        remoteChart: oci://registry-1.docker.io/bitnamicharts/mongodb
        namespace: mongodb
        createNamespace: true
        wait: true
        setValues:
          architecture: standalone
      
      - name: coder
        chartPath: ./charts/coder
        namespace: mongodb
        createNamespace: true
        setValues:
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: .
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
          
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
    hooks:
      after:
        - host:
            command: ["sh", "-c", "./get-secret.sh"]
            os: [darwin, linux]

portForward:
- resourceType: service
  resourceName: mongodb
  namespace: mongodb
  port: 27017
  localPort: 27017
- resourceType: service
  resourceName: code-server-service
  namespace: mongodb
  address: localhost
  port: 8080
  localPort: 8001